/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CouponCode {
  'id' : bigint,
  'expiresAt' : [] | [bigint],
  'code' : string,
  'createdAt' : Timestamp,
  'usedCount' : bigint,
  'description' : string,
  'isActive' : boolean,
  'maxUses' : [] | [bigint],
  'perkType' : CouponPerkType,
}
export type CouponPerkType = { 'custom' : string } |
  { 'freeMonths' : bigint } |
  { 'upgradeToPhaid' : null } |
  { 'featureUnlock' : Array<string> };
export interface CouponRedemptionResult {
  'perkApplied' : string,
  'coupon' : CouponCode,
}
export interface CouponStats {
  'coupon' : CouponCode,
  'totalRedemptions' : bigint,
}
export interface CreateCouponInput {
  'expiresAt' : [] | [bigint],
  'code' : string,
  'description' : string,
  'maxUses' : [] | [bigint],
  'perkType' : CouponPerkType,
}
export interface CsvTradeRow {
  'pnl' : [] | [number],
  'exitDate' : Timestamp,
  'direction' : Direction,
  'entryDate' : Timestamp,
  'chartImageUrl' : [] | [string],
  'sessionTime' : [] | [SessionTime],
  'pair' : string,
  'marketCondition' : [] | [MarketCondition],
  'riskReward' : [] | [number],
  'strategyTag' : [] | [string],
  'mistakeTag' : [] | [string],
  'notes' : [] | [string],
  'entryPrice' : number,
  'exitPrice' : number,
}
export type Direction = { 'LONG' : null } |
  { 'SHORT' : null };
export type ImportJobId = bigint;
export interface ImportJobPublic {
  'id' : ImportJobId,
  'status' : ImportStatus,
  'completedAt' : [] | [Timestamp],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'errors' : Array<ImportLineError>,
  'importedCount' : bigint,
}
export interface ImportLineError { 'lineNumber' : bigint, 'reason' : string }
export type ImportStatus = { 'FAILED' : null } |
  { 'PENDING' : null } |
  { 'PROCESSING' : null } |
  { 'COMPLETE' : null };
export type MarketCondition = { 'VOLATILE' : null } |
  { 'RANGING' : null } |
  { 'CHOPPY' : null } |
  { 'OTHER' : null } |
  { 'TRENDING' : null };
export interface PairStats {
  'tradeCount' : bigint,
  'pair' : string,
  'totalPnl' : number,
  'winRate' : number,
}
export interface PerformanceMetrics {
  'avgRiskReward' : number,
  'pnlBySession' : Array<SessionStats>,
  'computedAt' : Timestamp,
  'userId' : UserId,
  'bestPair' : [] | [string],
  'weeklyPnl' : Array<PnlDataPoint>,
  'worstPair' : [] | [string],
  'totalPnl' : number,
  'pnlByStrategy' : Array<StrategyStats>,
  'pnlByPair' : Array<PairStats>,
  'monthlyPnl' : Array<PnlDataPoint>,
  'winRate' : number,
  'maxDrawdown' : number,
}
export interface PnlDataPoint {
  'pnl' : number,
  'tradeCount' : bigint,
  'periodLabel' : string,
}
export interface SessionStats {
  'tradeCount' : bigint,
  'totalPnl' : number,
  'session' : SessionTime,
  'winRate' : number,
}
export type SessionTime = { 'NY' : null } |
  { 'LONDON' : null } |
  { 'ASIAN' : null } |
  { 'OTHER' : null };
export interface StrategyStats {
  'tag' : string,
  'tradeCount' : bigint,
  'totalPnl' : number,
  'winRate' : number,
}
export type Tier = { 'FREE' : null } |
  { 'PAID' : null };
export interface TierLimitStatus {
  'dailyCount' : bigint,
  'tier' : Tier,
  'totalCount' : bigint,
  'dailyLimitReached' : boolean,
  'dailyLimit' : bigint,
  'totalLimit' : bigint,
  'totalLimitReached' : boolean,
}
export type Timestamp = bigint;
export interface TradeFilter {
  'dateTo' : [] | [Timestamp],
  'sessionTime' : [] | [SessionTime],
  'pair' : [] | [string],
  'strategyTag' : [] | [string],
  'mistakeTag' : [] | [string],
  'dateFrom' : [] | [Timestamp],
}
export type TradeId = bigint;
export interface TradeInput {
  'exitDate' : Timestamp,
  'direction' : Direction,
  'entryDate' : Timestamp,
  'chartImageUrl' : [] | [string],
  'sessionTime' : SessionTime,
  'takeProfit' : [] | [number],
  'pair' : string,
  'marketCondition' : MarketCondition,
  'strategyTag' : string,
  'mistakeTag' : [] | [string],
  'stopLoss' : [] | [number],
  'notes' : string,
  'entryPrice' : number,
  'exitPrice' : number,
}
export interface TradePublic {
  'id' : TradeId,
  'pnl' : number,
  'exitDate' : Timestamp,
  'direction' : Direction,
  'entryDate' : Timestamp,
  'chartImageUrl' : [] | [string],
  'sessionTime' : SessionTime,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'pair' : string,
  'marketCondition' : MarketCondition,
  'riskReward' : number,
  'strategyTag' : string,
  'updatedAt' : Timestamp,
  'mistakeTag' : [] | [string],
  'notes' : string,
  'entryPrice' : number,
  'exitPrice' : number,
}
export type UserId = Principal;
export interface UserPublic {
  'id' : UserId,
  'paidUntil' : [] | [bigint],
  'createdAt' : Timestamp,
  'tier' : Tier,
  'stripeCustomerId' : [] | [string],
  'isAdmin' : boolean,
  'unlockedFeatures' : Array<string>,
}
export interface _SERVICE {
  'bulkImportTrades' : ActorMethod<[Array<CsvTradeRow>], ImportJobPublic>,
  'computeMetrics' : ActorMethod<[], PerformanceMetrics>,
  'createCoupon' : ActorMethod<[CreateCouponInput], CouponCode>,
  'createTrade' : ActorMethod<
    [TradeInput],
    { 'ok' : TradePublic } |
      { 'limitReached' : string }
  >,
  'deactivateCoupon' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteTrade' : ActorMethod<[TradeId], boolean>,
  'getCouponStats' : ActorMethod<
    [bigint],
    { 'ok' : CouponStats } |
      { 'err' : string }
  >,
  'getImportJob' : ActorMethod<[ImportJobId], [] | [ImportJobPublic]>,
  'getMetrics' : ActorMethod<[], [] | [PerformanceMetrics]>,
  'getOrCreateUser' : ActorMethod<[], UserPublic>,
  'getTrade' : ActorMethod<[TradeId], [] | [TradePublic]>,
  'getTradeLimitStatus' : ActorMethod<[], TierLimitStatus>,
  'getTrades' : ActorMethod<[TradeFilter], Array<TradePublic>>,
  'getUserTier' : ActorMethod<[], Tier>,
  'isAdmin' : ActorMethod<[], boolean>,
  'listCoupons' : ActorMethod<[], Array<CouponCode>>,
  'redeemCoupon' : ActorMethod<
    [string],
    { 'ok' : CouponRedemptionResult } |
      { 'err' : string }
  >,
  'saveChartAnnotation' : ActorMethod<[TradeId, string], [] | [TradePublic]>,
  'setAdmin' : ActorMethod<[Principal], { 'ok' : null } | { 'err' : string }>,
  'updateTrade' : ActorMethod<[TradeId, TradeInput], [] | [TradePublic]>,
  'upgradeToPaid' : ActorMethod<[], UserPublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];