/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Direction = IDL.Variant({ 'LONG' : IDL.Null, 'SHORT' : IDL.Null });
export const SessionTime = IDL.Variant({
  'NY' : IDL.Null,
  'LONDON' : IDL.Null,
  'ASIAN' : IDL.Null,
  'OTHER' : IDL.Null,
});
export const MarketCondition = IDL.Variant({
  'VOLATILE' : IDL.Null,
  'RANGING' : IDL.Null,
  'CHOPPY' : IDL.Null,
  'OTHER' : IDL.Null,
  'TRENDING' : IDL.Null,
});
export const CsvTradeRow = IDL.Record({
  'pnl' : IDL.Opt(IDL.Float64),
  'exitDate' : Timestamp,
  'direction' : Direction,
  'entryDate' : Timestamp,
  'chartImageUrl' : IDL.Opt(IDL.Text),
  'sessionTime' : IDL.Opt(SessionTime),
  'pair' : IDL.Text,
  'marketCondition' : IDL.Opt(MarketCondition),
  'riskReward' : IDL.Opt(IDL.Float64),
  'strategyTag' : IDL.Opt(IDL.Text),
  'mistakeTag' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Float64,
});
export const ImportJobId = IDL.Nat;
export const ImportStatus = IDL.Variant({
  'FAILED' : IDL.Null,
  'PENDING' : IDL.Null,
  'PROCESSING' : IDL.Null,
  'COMPLETE' : IDL.Null,
});
export const UserId = IDL.Principal;
export const ImportLineError = IDL.Record({
  'lineNumber' : IDL.Nat,
  'reason' : IDL.Text,
});
export const ImportJobPublic = IDL.Record({
  'id' : ImportJobId,
  'status' : ImportStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'errors' : IDL.Vec(ImportLineError),
  'importedCount' : IDL.Nat,
});
export const SessionStats = IDL.Record({
  'tradeCount' : IDL.Nat,
  'totalPnl' : IDL.Float64,
  'session' : SessionTime,
  'winRate' : IDL.Float64,
});
export const PnlDataPoint = IDL.Record({
  'pnl' : IDL.Float64,
  'tradeCount' : IDL.Nat,
  'periodLabel' : IDL.Text,
});
export const StrategyStats = IDL.Record({
  'tag' : IDL.Text,
  'tradeCount' : IDL.Nat,
  'totalPnl' : IDL.Float64,
  'winRate' : IDL.Float64,
});
export const PairStats = IDL.Record({
  'tradeCount' : IDL.Nat,
  'pair' : IDL.Text,
  'totalPnl' : IDL.Float64,
  'winRate' : IDL.Float64,
});
export const PerformanceMetrics = IDL.Record({
  'avgRiskReward' : IDL.Float64,
  'pnlBySession' : IDL.Vec(SessionStats),
  'computedAt' : Timestamp,
  'userId' : UserId,
  'bestPair' : IDL.Opt(IDL.Text),
  'weeklyPnl' : IDL.Vec(PnlDataPoint),
  'worstPair' : IDL.Opt(IDL.Text),
  'totalPnl' : IDL.Float64,
  'pnlByStrategy' : IDL.Vec(StrategyStats),
  'pnlByPair' : IDL.Vec(PairStats),
  'monthlyPnl' : IDL.Vec(PnlDataPoint),
  'winRate' : IDL.Float64,
  'maxDrawdown' : IDL.Float64,
});
export const TradeInput = IDL.Record({
  'exitDate' : Timestamp,
  'direction' : Direction,
  'entryDate' : Timestamp,
  'chartImageUrl' : IDL.Opt(IDL.Text),
  'sessionTime' : SessionTime,
  'takeProfit' : IDL.Opt(IDL.Float64),
  'pair' : IDL.Text,
  'marketCondition' : MarketCondition,
  'strategyTag' : IDL.Text,
  'mistakeTag' : IDL.Opt(IDL.Text),
  'stopLoss' : IDL.Opt(IDL.Float64),
  'notes' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Float64,
});
export const TradeId = IDL.Nat;
export const TradePublic = IDL.Record({
  'id' : TradeId,
  'pnl' : IDL.Float64,
  'exitDate' : Timestamp,
  'direction' : Direction,
  'entryDate' : Timestamp,
  'chartImageUrl' : IDL.Opt(IDL.Text),
  'sessionTime' : SessionTime,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'pair' : IDL.Text,
  'marketCondition' : MarketCondition,
  'riskReward' : IDL.Float64,
  'strategyTag' : IDL.Text,
  'updatedAt' : Timestamp,
  'mistakeTag' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Float64,
});
export const Tier = IDL.Variant({ 'FREE' : IDL.Null, 'PAID' : IDL.Null });
export const UserPublic = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'tier' : Tier,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
});
export const TierLimitStatus = IDL.Record({
  'dailyCount' : IDL.Nat,
  'tier' : Tier,
  'totalCount' : IDL.Nat,
  'dailyLimitReached' : IDL.Bool,
  'dailyLimit' : IDL.Nat,
  'totalLimit' : IDL.Nat,
  'totalLimitReached' : IDL.Bool,
});
export const TradeFilter = IDL.Record({
  'dateTo' : IDL.Opt(Timestamp),
  'sessionTime' : IDL.Opt(SessionTime),
  'pair' : IDL.Opt(IDL.Text),
  'strategyTag' : IDL.Opt(IDL.Text),
  'mistakeTag' : IDL.Opt(IDL.Text),
  'dateFrom' : IDL.Opt(Timestamp),
});

export const idlService = IDL.Service({
  'bulkImportTrades' : IDL.Func([IDL.Vec(CsvTradeRow)], [ImportJobPublic], []),
  'computeMetrics' : IDL.Func([], [PerformanceMetrics], []),
  'createTrade' : IDL.Func(
      [TradeInput],
      [IDL.Variant({ 'ok' : TradePublic, 'limitReached' : IDL.Text })],
      [],
    ),
  'deleteTrade' : IDL.Func([TradeId], [IDL.Bool], []),
  'getImportJob' : IDL.Func(
      [ImportJobId],
      [IDL.Opt(ImportJobPublic)],
      ['query'],
    ),
  'getMetrics' : IDL.Func([], [IDL.Opt(PerformanceMetrics)], ['query']),
  'getOrCreateUser' : IDL.Func([], [UserPublic], []),
  'getTrade' : IDL.Func([TradeId], [IDL.Opt(TradePublic)], ['query']),
  'getTradeLimitStatus' : IDL.Func([], [TierLimitStatus], ['query']),
  'getTrades' : IDL.Func([TradeFilter], [IDL.Vec(TradePublic)], ['query']),
  'getUserTier' : IDL.Func([], [Tier], ['query']),
  'saveChartAnnotation' : IDL.Func(
      [TradeId, IDL.Text],
      [IDL.Opt(TradePublic)],
      [],
    ),
  'updateTrade' : IDL.Func([TradeId, TradeInput], [IDL.Opt(TradePublic)], []),
  'upgradeToPaid' : IDL.Func([], [UserPublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Direction = IDL.Variant({ 'LONG' : IDL.Null, 'SHORT' : IDL.Null });
  const SessionTime = IDL.Variant({
    'NY' : IDL.Null,
    'LONDON' : IDL.Null,
    'ASIAN' : IDL.Null,
    'OTHER' : IDL.Null,
  });
  const MarketCondition = IDL.Variant({
    'VOLATILE' : IDL.Null,
    'RANGING' : IDL.Null,
    'CHOPPY' : IDL.Null,
    'OTHER' : IDL.Null,
    'TRENDING' : IDL.Null,
  });
  const CsvTradeRow = IDL.Record({
    'pnl' : IDL.Opt(IDL.Float64),
    'exitDate' : Timestamp,
    'direction' : Direction,
    'entryDate' : Timestamp,
    'chartImageUrl' : IDL.Opt(IDL.Text),
    'sessionTime' : IDL.Opt(SessionTime),
    'pair' : IDL.Text,
    'marketCondition' : IDL.Opt(MarketCondition),
    'riskReward' : IDL.Opt(IDL.Float64),
    'strategyTag' : IDL.Opt(IDL.Text),
    'mistakeTag' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Float64,
  });
  const ImportJobId = IDL.Nat;
  const ImportStatus = IDL.Variant({
    'FAILED' : IDL.Null,
    'PENDING' : IDL.Null,
    'PROCESSING' : IDL.Null,
    'COMPLETE' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const ImportLineError = IDL.Record({
    'lineNumber' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const ImportJobPublic = IDL.Record({
    'id' : ImportJobId,
    'status' : ImportStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'errors' : IDL.Vec(ImportLineError),
    'importedCount' : IDL.Nat,
  });
  const SessionStats = IDL.Record({
    'tradeCount' : IDL.Nat,
    'totalPnl' : IDL.Float64,
    'session' : SessionTime,
    'winRate' : IDL.Float64,
  });
  const PnlDataPoint = IDL.Record({
    'pnl' : IDL.Float64,
    'tradeCount' : IDL.Nat,
    'periodLabel' : IDL.Text,
  });
  const StrategyStats = IDL.Record({
    'tag' : IDL.Text,
    'tradeCount' : IDL.Nat,
    'totalPnl' : IDL.Float64,
    'winRate' : IDL.Float64,
  });
  const PairStats = IDL.Record({
    'tradeCount' : IDL.Nat,
    'pair' : IDL.Text,
    'totalPnl' : IDL.Float64,
    'winRate' : IDL.Float64,
  });
  const PerformanceMetrics = IDL.Record({
    'avgRiskReward' : IDL.Float64,
    'pnlBySession' : IDL.Vec(SessionStats),
    'computedAt' : Timestamp,
    'userId' : UserId,
    'bestPair' : IDL.Opt(IDL.Text),
    'weeklyPnl' : IDL.Vec(PnlDataPoint),
    'worstPair' : IDL.Opt(IDL.Text),
    'totalPnl' : IDL.Float64,
    'pnlByStrategy' : IDL.Vec(StrategyStats),
    'pnlByPair' : IDL.Vec(PairStats),
    'monthlyPnl' : IDL.Vec(PnlDataPoint),
    'winRate' : IDL.Float64,
    'maxDrawdown' : IDL.Float64,
  });
  const TradeInput = IDL.Record({
    'exitDate' : Timestamp,
    'direction' : Direction,
    'entryDate' : Timestamp,
    'chartImageUrl' : IDL.Opt(IDL.Text),
    'sessionTime' : SessionTime,
    'takeProfit' : IDL.Opt(IDL.Float64),
    'pair' : IDL.Text,
    'marketCondition' : MarketCondition,
    'strategyTag' : IDL.Text,
    'mistakeTag' : IDL.Opt(IDL.Text),
    'stopLoss' : IDL.Opt(IDL.Float64),
    'notes' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Float64,
  });
  const TradeId = IDL.Nat;
  const TradePublic = IDL.Record({
    'id' : TradeId,
    'pnl' : IDL.Float64,
    'exitDate' : Timestamp,
    'direction' : Direction,
    'entryDate' : Timestamp,
    'chartImageUrl' : IDL.Opt(IDL.Text),
    'sessionTime' : SessionTime,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'pair' : IDL.Text,
    'marketCondition' : MarketCondition,
    'riskReward' : IDL.Float64,
    'strategyTag' : IDL.Text,
    'updatedAt' : Timestamp,
    'mistakeTag' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Float64,
  });
  const Tier = IDL.Variant({ 'FREE' : IDL.Null, 'PAID' : IDL.Null });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'tier' : Tier,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
  });
  const TierLimitStatus = IDL.Record({
    'dailyCount' : IDL.Nat,
    'tier' : Tier,
    'totalCount' : IDL.Nat,
    'dailyLimitReached' : IDL.Bool,
    'dailyLimit' : IDL.Nat,
    'totalLimit' : IDL.Nat,
    'totalLimitReached' : IDL.Bool,
  });
  const TradeFilter = IDL.Record({
    'dateTo' : IDL.Opt(Timestamp),
    'sessionTime' : IDL.Opt(SessionTime),
    'pair' : IDL.Opt(IDL.Text),
    'strategyTag' : IDL.Opt(IDL.Text),
    'mistakeTag' : IDL.Opt(IDL.Text),
    'dateFrom' : IDL.Opt(Timestamp),
  });
  
  return IDL.Service({
    'bulkImportTrades' : IDL.Func(
        [IDL.Vec(CsvTradeRow)],
        [ImportJobPublic],
        [],
      ),
    'computeMetrics' : IDL.Func([], [PerformanceMetrics], []),
    'createTrade' : IDL.Func(
        [TradeInput],
        [IDL.Variant({ 'ok' : TradePublic, 'limitReached' : IDL.Text })],
        [],
      ),
    'deleteTrade' : IDL.Func([TradeId], [IDL.Bool], []),
    'getImportJob' : IDL.Func(
        [ImportJobId],
        [IDL.Opt(ImportJobPublic)],
        ['query'],
      ),
    'getMetrics' : IDL.Func([], [IDL.Opt(PerformanceMetrics)], ['query']),
    'getOrCreateUser' : IDL.Func([], [UserPublic], []),
    'getTrade' : IDL.Func([TradeId], [IDL.Opt(TradePublic)], ['query']),
    'getTradeLimitStatus' : IDL.Func([], [TierLimitStatus], ['query']),
    'getTrades' : IDL.Func([TradeFilter], [IDL.Vec(TradePublic)], ['query']),
    'getUserTier' : IDL.Func([], [Tier], ['query']),
    'saveChartAnnotation' : IDL.Func(
        [TradeId, IDL.Text],
        [IDL.Opt(TradePublic)],
        [],
      ),
    'updateTrade' : IDL.Func([TradeId, TradeInput], [IDL.Opt(TradePublic)], []),
    'upgradeToPaid' : IDL.Func([], [UserPublic], []),
  });
};

export const init = ({ IDL }) => { return []; };