/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface UserPublic {
    id: UserId;
    createdAt: Timestamp;
    tier: Tier;
    stripeCustomerId?: string;
}
export interface TierLimitStatus {
    dailyCount: bigint;
    tier: Tier;
    totalCount: bigint;
    dailyLimitReached: boolean;
    dailyLimit: bigint;
    totalLimit: bigint;
    totalLimitReached: boolean;
}
export interface TradePublic {
    id: TradeId;
    pnl: number;
    exitDate: Timestamp;
    direction: Direction;
    entryDate: Timestamp;
    chartImageUrl?: string;
    sessionTime: SessionTime;
    userId: UserId;
    createdAt: Timestamp;
    pair: string;
    marketCondition: MarketCondition;
    riskReward: number;
    strategyTag: string;
    updatedAt: Timestamp;
    mistakeTag?: string;
    notes: string;
    entryPrice: number;
    exitPrice: number;
}
export type TradeId = bigint;
export interface PnlDataPoint {
    pnl: number;
    tradeCount: bigint;
    periodLabel: string;
}
export interface TradeFilter {
    dateTo?: Timestamp;
    sessionTime?: SessionTime;
    pair?: string;
    strategyTag?: string;
    mistakeTag?: string;
    dateFrom?: Timestamp;
}
export interface PerformanceMetrics {
    avgRiskReward: number;
    pnlBySession: Array<SessionStats>;
    computedAt: Timestamp;
    userId: UserId;
    bestPair?: string;
    weeklyPnl: Array<PnlDataPoint>;
    worstPair?: string;
    totalPnl: number;
    pnlByStrategy: Array<StrategyStats>;
    pnlByPair: Array<PairStats>;
    monthlyPnl: Array<PnlDataPoint>;
    winRate: number;
    maxDrawdown: number;
}
export interface CsvTradeRow {
    pnl?: number;
    exitDate: Timestamp;
    direction: Direction;
    entryDate: Timestamp;
    chartImageUrl?: string;
    sessionTime?: SessionTime;
    pair: string;
    marketCondition?: MarketCondition;
    riskReward?: number;
    strategyTag?: string;
    mistakeTag?: string;
    notes?: string;
    entryPrice: number;
    exitPrice: number;
}
export interface ImportJobPublic {
    id: ImportJobId;
    status: ImportStatus;
    completedAt?: Timestamp;
    userId: UserId;
    createdAt: Timestamp;
    errors: Array<ImportLineError>;
    importedCount: bigint;
}
export type UserId = Principal;
export type ImportJobId = bigint;
export interface TradeInput {
    exitDate: Timestamp;
    direction: Direction;
    entryDate: Timestamp;
    chartImageUrl?: string;
    sessionTime: SessionTime;
    takeProfit?: number;
    pair: string;
    marketCondition: MarketCondition;
    strategyTag: string;
    mistakeTag?: string;
    stopLoss?: number;
    notes: string;
    entryPrice: number;
    exitPrice: number;
}
export interface SessionStats {
    tradeCount: bigint;
    totalPnl: number;
    session: SessionTime;
    winRate: number;
}
export interface PairStats {
    tradeCount: bigint;
    pair: string;
    totalPnl: number;
    winRate: number;
}
export interface StrategyStats {
    tag: string;
    tradeCount: bigint;
    totalPnl: number;
    winRate: number;
}
export interface ImportLineError {
    lineNumber: bigint;
    reason: string;
}
export enum Direction {
    LONG = "LONG",
    SHORT = "SHORT"
}
export enum ImportStatus {
    FAILED = "FAILED",
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    COMPLETE = "COMPLETE"
}
export enum MarketCondition {
    VOLATILE = "VOLATILE",
    RANGING = "RANGING",
    CHOPPY = "CHOPPY",
    OTHER = "OTHER",
    TRENDING = "TRENDING"
}
export enum SessionTime {
    NY = "NY",
    LONDON = "LONDON",
    ASIAN = "ASIAN",
    OTHER = "OTHER"
}
export enum Tier {
    FREE = "FREE",
    PAID = "PAID"
}
export interface backendInterface {
    bulkImportTrades(rows: Array<CsvTradeRow>): Promise<ImportJobPublic>;
    computeMetrics(): Promise<PerformanceMetrics>;
    createTrade(input: TradeInput): Promise<{
        __kind__: "ok";
        ok: TradePublic;
    } | {
        __kind__: "limitReached";
        limitReached: string;
    }>;
    deleteTrade(tradeId: TradeId): Promise<boolean>;
    getImportJob(jobId: ImportJobId): Promise<ImportJobPublic | null>;
    getMetrics(): Promise<PerformanceMetrics | null>;
    getOrCreateUser(): Promise<UserPublic>;
    getTrade(tradeId: TradeId): Promise<TradePublic | null>;
    getTradeLimitStatus(): Promise<TierLimitStatus>;
    getTrades(filter: TradeFilter): Promise<Array<TradePublic>>;
    getUserTier(): Promise<Tier>;
    saveChartAnnotation(tradeId: TradeId, imageUrl: string): Promise<TradePublic | null>;
    updateTrade(tradeId: TradeId, input: TradeInput): Promise<TradePublic | null>;
    upgradeToPaid(): Promise<UserPublic>;
}
import type { CsvTradeRow as _CsvTradeRow, Direction as _Direction, ImportJobId as _ImportJobId, ImportJobPublic as _ImportJobPublic, ImportLineError as _ImportLineError, ImportStatus as _ImportStatus, MarketCondition as _MarketCondition, PairStats as _PairStats, PerformanceMetrics as _PerformanceMetrics, PnlDataPoint as _PnlDataPoint, SessionStats as _SessionStats, SessionTime as _SessionTime, StrategyStats as _StrategyStats, Tier as _Tier, TierLimitStatus as _TierLimitStatus, Timestamp as _Timestamp, TradeFilter as _TradeFilter, TradeId as _TradeId, TradeInput as _TradeInput, TradePublic as _TradePublic, UserId as _UserId, UserPublic as _UserPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bulkImportTrades(arg0: Array<CsvTradeRow>): Promise<ImportJobPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportTrades(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ImportJobPublic_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportTrades(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ImportJobPublic_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async computeMetrics(): Promise<PerformanceMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.computeMetrics();
                return from_candid_PerformanceMetrics_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeMetrics();
            return from_candid_PerformanceMetrics_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTrade(arg0: TradeInput): Promise<{
        __kind__: "ok";
        ok: TradePublic;
    } | {
        __kind__: "limitReached";
        limitReached: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrade(to_candid_TradeInput_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrade(to_candid_TradeInput_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTrade(arg0: TradeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrade(arg0);
            return result;
        }
    }
    async getImportJob(arg0: ImportJobId): Promise<ImportJobPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getImportJob(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImportJob(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetrics(): Promise<PerformanceMetrics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateUser(): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateUser();
                return from_candid_UserPublic_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateUser();
            return from_candid_UserPublic_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrade(arg0: TradeId): Promise<TradePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrade(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrade(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeLimitStatus(): Promise<TierLimitStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeLimitStatus();
                return from_candid_TierLimitStatus_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeLimitStatus();
            return from_candid_TierLimitStatus_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrades(arg0: TradeFilter): Promise<Array<TradePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrades(to_candid_TradeFilter_n41(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrades(to_candid_TradeFilter_n41(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTier(): Promise<Tier> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTier();
                return from_candid_Tier_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTier();
            return from_candid_Tier_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveChartAnnotation(arg0: TradeId, arg1: string): Promise<TradePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.saveChartAnnotation(arg0, arg1);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveChartAnnotation(arg0, arg1);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTrade(arg0: TradeId, arg1: TradeInput): Promise<TradePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrade(arg0, to_candid_TradeInput_n23(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrade(arg0, to_candid_TradeInput_n23(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async upgradeToPaid(): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeToPaid();
                return from_candid_UserPublic_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeToPaid();
            return from_candid_UserPublic_n34(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Direction_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ImportJobPublic_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImportJobPublic): ImportJobPublic {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ImportStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImportStatus): ImportStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_MarketCondition_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketCondition): MarketCondition {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PerformanceMetrics_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PerformanceMetrics): PerformanceMetrics {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStats_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStats): SessionStats {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SessionTime_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionTime): SessionTime {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TierLimitStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TierLimitStatus): TierLimitStatus {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Tier_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tier): Tier {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_TradePublic_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradePublic): TradePublic {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImportJobPublic]): ImportJobPublic | null {
    return value.length === 0 ? null : from_candid_ImportJobPublic_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PerformanceMetrics]): PerformanceMetrics | null {
    return value.length === 0 ? null : from_candid_PerformanceMetrics_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TradePublic]): TradePublic | null {
    return value.length === 0 ? null : from_candid_TradePublic_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ImportJobId;
    status: _ImportStatus;
    completedAt: [] | [_Timestamp];
    userId: _UserId;
    createdAt: _Timestamp;
    errors: Array<_ImportLineError>;
    importedCount: bigint;
}): {
    id: ImportJobId;
    status: ImportStatus;
    completedAt?: Timestamp;
    userId: UserId;
    createdAt: Timestamp;
    errors: Array<ImportLineError>;
    importedCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ImportStatus_n12(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.completedAt)),
        userId: value.userId,
        createdAt: value.createdAt,
        errors: value.errors,
        importedCount: value.importedCount
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    avgRiskReward: number;
    pnlBySession: Array<_SessionStats>;
    computedAt: _Timestamp;
    userId: _UserId;
    bestPair: [] | [string];
    weeklyPnl: Array<_PnlDataPoint>;
    worstPair: [] | [string];
    totalPnl: number;
    pnlByStrategy: Array<_StrategyStats>;
    pnlByPair: Array<_PairStats>;
    monthlyPnl: Array<_PnlDataPoint>;
    winRate: number;
    maxDrawdown: number;
}): {
    avgRiskReward: number;
    pnlBySession: Array<SessionStats>;
    computedAt: Timestamp;
    userId: UserId;
    bestPair?: string;
    weeklyPnl: Array<PnlDataPoint>;
    worstPair?: string;
    totalPnl: number;
    pnlByStrategy: Array<StrategyStats>;
    pnlByPair: Array<PairStats>;
    monthlyPnl: Array<PnlDataPoint>;
    winRate: number;
    maxDrawdown: number;
} {
    return {
        avgRiskReward: value.avgRiskReward,
        pnlBySession: from_candid_vec_n17(_uploadFile, _downloadFile, value.pnlBySession),
        computedAt: value.computedAt,
        userId: value.userId,
        bestPair: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.bestPair)),
        weeklyPnl: value.weeklyPnl,
        worstPair: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.worstPair)),
        totalPnl: value.totalPnl,
        pnlByStrategy: value.pnlByStrategy,
        pnlByPair: value.pnlByPair,
        monthlyPnl: value.monthlyPnl,
        winRate: value.winRate,
        maxDrawdown: value.maxDrawdown
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tradeCount: bigint;
    totalPnl: number;
    session: _SessionTime;
    winRate: number;
}): {
    tradeCount: bigint;
    totalPnl: number;
    session: SessionTime;
    winRate: number;
} {
    return {
        tradeCount: value.tradeCount,
        totalPnl: value.totalPnl,
        session: from_candid_SessionTime_n20(_uploadFile, _downloadFile, value.session),
        winRate: value.winRate
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TradeId;
    pnl: number;
    exitDate: _Timestamp;
    direction: _Direction;
    entryDate: _Timestamp;
    chartImageUrl: [] | [string];
    sessionTime: _SessionTime;
    userId: _UserId;
    createdAt: _Timestamp;
    pair: string;
    marketCondition: _MarketCondition;
    riskReward: number;
    strategyTag: string;
    updatedAt: _Timestamp;
    mistakeTag: [] | [string];
    notes: string;
    entryPrice: number;
    exitPrice: number;
}): {
    id: TradeId;
    pnl: number;
    exitDate: Timestamp;
    direction: Direction;
    entryDate: Timestamp;
    chartImageUrl?: string;
    sessionTime: SessionTime;
    userId: UserId;
    createdAt: Timestamp;
    pair: string;
    marketCondition: MarketCondition;
    riskReward: number;
    strategyTag: string;
    updatedAt: Timestamp;
    mistakeTag?: string;
    notes: string;
    entryPrice: number;
    exitPrice: number;
} {
    return {
        id: value.id,
        pnl: value.pnl,
        exitDate: value.exitDate,
        direction: from_candid_Direction_n28(_uploadFile, _downloadFile, value.direction),
        entryDate: value.entryDate,
        chartImageUrl: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.chartImageUrl)),
        sessionTime: from_candid_SessionTime_n20(_uploadFile, _downloadFile, value.sessionTime),
        userId: value.userId,
        createdAt: value.createdAt,
        pair: value.pair,
        marketCondition: from_candid_MarketCondition_n30(_uploadFile, _downloadFile, value.marketCondition),
        riskReward: value.riskReward,
        strategyTag: value.strategyTag,
        updatedAt: value.updatedAt,
        mistakeTag: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.mistakeTag)),
        notes: value.notes,
        entryPrice: value.entryPrice,
        exitPrice: value.exitPrice
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    createdAt: _Timestamp;
    tier: _Tier;
    stripeCustomerId: [] | [string];
}): {
    id: UserId;
    createdAt: Timestamp;
    tier: Tier;
    stripeCustomerId?: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        tier: from_candid_Tier_n36(_uploadFile, _downloadFile, value.tier),
        stripeCustomerId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.stripeCustomerId))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dailyCount: bigint;
    tier: _Tier;
    totalCount: bigint;
    dailyLimitReached: boolean;
    dailyLimit: bigint;
    totalLimit: bigint;
    totalLimitReached: boolean;
}): {
    dailyCount: bigint;
    tier: Tier;
    totalCount: bigint;
    dailyLimitReached: boolean;
    dailyLimit: bigint;
    totalLimit: bigint;
    totalLimitReached: boolean;
} {
    return {
        dailyCount: value.dailyCount,
        tier: from_candid_Tier_n36(_uploadFile, _downloadFile, value.tier),
        totalCount: value.totalCount,
        dailyLimitReached: value.dailyLimitReached,
        dailyLimit: value.dailyLimit,
        totalLimit: value.totalLimit,
        totalLimitReached: value.totalLimitReached
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FAILED: null;
} | {
    PENDING: null;
} | {
    PROCESSING: null;
} | {
    COMPLETE: null;
}): ImportStatus {
    return "FAILED" in value ? ImportStatus.FAILED : "PENDING" in value ? ImportStatus.PENDING : "PROCESSING" in value ? ImportStatus.PROCESSING : "COMPLETE" in value ? ImportStatus.COMPLETE : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NY: null;
} | {
    LONDON: null;
} | {
    ASIAN: null;
} | {
    OTHER: null;
}): SessionTime {
    return "NY" in value ? SessionTime.NY : "LONDON" in value ? SessionTime.LONDON : "ASIAN" in value ? SessionTime.ASIAN : "OTHER" in value ? SessionTime.OTHER : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TradePublic;
} | {
    limitReached: string;
}): {
    __kind__: "ok";
    ok: TradePublic;
} | {
    __kind__: "limitReached";
    limitReached: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TradePublic_n26(_uploadFile, _downloadFile, value.ok)
    } : "limitReached" in value ? {
        __kind__: "limitReached",
        limitReached: value.limitReached
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    LONG: null;
} | {
    SHORT: null;
}): Direction {
    return "LONG" in value ? Direction.LONG : "SHORT" in value ? Direction.SHORT : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    VOLATILE: null;
} | {
    RANGING: null;
} | {
    CHOPPY: null;
} | {
    OTHER: null;
} | {
    TRENDING: null;
}): MarketCondition {
    return "VOLATILE" in value ? MarketCondition.VOLATILE : "RANGING" in value ? MarketCondition.RANGING : "CHOPPY" in value ? MarketCondition.CHOPPY : "OTHER" in value ? MarketCondition.OTHER : "TRENDING" in value ? MarketCondition.TRENDING : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FREE: null;
} | {
    PAID: null;
}): Tier {
    return "FREE" in value ? Tier.FREE : "PAID" in value ? Tier.PAID : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SessionStats>): Array<SessionStats> {
    return value.map((x)=>from_candid_SessionStats_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradePublic>): Array<TradePublic> {
    return value.map((x)=>from_candid_TradePublic_n26(_uploadFile, _downloadFile, x));
}
function to_candid_CsvTradeRow_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CsvTradeRow): _CsvTradeRow {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_Direction_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_MarketCondition_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketCondition): _MarketCondition {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SessionTime_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionTime): _SessionTime {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_TradeFilter_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeFilter): _TradeFilter {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_TradeInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeInput): _TradeInput {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exitDate: Timestamp;
    direction: Direction;
    entryDate: Timestamp;
    chartImageUrl?: string;
    sessionTime: SessionTime;
    takeProfit?: number;
    pair: string;
    marketCondition: MarketCondition;
    strategyTag: string;
    mistakeTag?: string;
    stopLoss?: number;
    notes: string;
    entryPrice: number;
    exitPrice: number;
}): {
    exitDate: _Timestamp;
    direction: _Direction;
    entryDate: _Timestamp;
    chartImageUrl: [] | [string];
    sessionTime: _SessionTime;
    takeProfit: [] | [number];
    pair: string;
    marketCondition: _MarketCondition;
    strategyTag: string;
    mistakeTag: [] | [string];
    stopLoss: [] | [number];
    notes: string;
    entryPrice: number;
    exitPrice: number;
} {
    return {
        exitDate: value.exitDate,
        direction: to_candid_Direction_n4(_uploadFile, _downloadFile, value.direction),
        entryDate: value.entryDate,
        chartImageUrl: value.chartImageUrl ? candid_some(value.chartImageUrl) : candid_none(),
        sessionTime: to_candid_SessionTime_n6(_uploadFile, _downloadFile, value.sessionTime),
        takeProfit: value.takeProfit ? candid_some(value.takeProfit) : candid_none(),
        pair: value.pair,
        marketCondition: to_candid_MarketCondition_n8(_uploadFile, _downloadFile, value.marketCondition),
        strategyTag: value.strategyTag,
        mistakeTag: value.mistakeTag ? candid_some(value.mistakeTag) : candid_none(),
        stopLoss: value.stopLoss ? candid_some(value.stopLoss) : candid_none(),
        notes: value.notes,
        entryPrice: value.entryPrice,
        exitPrice: value.exitPrice
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pnl?: number;
    exitDate: Timestamp;
    direction: Direction;
    entryDate: Timestamp;
    chartImageUrl?: string;
    sessionTime?: SessionTime;
    pair: string;
    marketCondition?: MarketCondition;
    riskReward?: number;
    strategyTag?: string;
    mistakeTag?: string;
    notes?: string;
    entryPrice: number;
    exitPrice: number;
}): {
    pnl: [] | [number];
    exitDate: _Timestamp;
    direction: _Direction;
    entryDate: _Timestamp;
    chartImageUrl: [] | [string];
    sessionTime: [] | [_SessionTime];
    pair: string;
    marketCondition: [] | [_MarketCondition];
    riskReward: [] | [number];
    strategyTag: [] | [string];
    mistakeTag: [] | [string];
    notes: [] | [string];
    entryPrice: number;
    exitPrice: number;
} {
    return {
        pnl: value.pnl ? candid_some(value.pnl) : candid_none(),
        exitDate: value.exitDate,
        direction: to_candid_Direction_n4(_uploadFile, _downloadFile, value.direction),
        entryDate: value.entryDate,
        chartImageUrl: value.chartImageUrl ? candid_some(value.chartImageUrl) : candid_none(),
        sessionTime: value.sessionTime ? candid_some(to_candid_SessionTime_n6(_uploadFile, _downloadFile, value.sessionTime)) : candid_none(),
        pair: value.pair,
        marketCondition: value.marketCondition ? candid_some(to_candid_MarketCondition_n8(_uploadFile, _downloadFile, value.marketCondition)) : candid_none(),
        riskReward: value.riskReward ? candid_some(value.riskReward) : candid_none(),
        strategyTag: value.strategyTag ? candid_some(value.strategyTag) : candid_none(),
        mistakeTag: value.mistakeTag ? candid_some(value.mistakeTag) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        entryPrice: value.entryPrice,
        exitPrice: value.exitPrice
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateTo?: Timestamp;
    sessionTime?: SessionTime;
    pair?: string;
    strategyTag?: string;
    mistakeTag?: string;
    dateFrom?: Timestamp;
}): {
    dateTo: [] | [_Timestamp];
    sessionTime: [] | [_SessionTime];
    pair: [] | [string];
    strategyTag: [] | [string];
    mistakeTag: [] | [string];
    dateFrom: [] | [_Timestamp];
} {
    return {
        dateTo: value.dateTo ? candid_some(value.dateTo) : candid_none(),
        sessionTime: value.sessionTime ? candid_some(to_candid_SessionTime_n6(_uploadFile, _downloadFile, value.sessionTime)) : candid_none(),
        pair: value.pair ? candid_some(value.pair) : candid_none(),
        strategyTag: value.strategyTag ? candid_some(value.strategyTag) : candid_none(),
        mistakeTag: value.mistakeTag ? candid_some(value.mistakeTag) : candid_none(),
        dateFrom: value.dateFrom ? candid_some(value.dateFrom) : candid_none()
    };
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    LONG: null;
} | {
    SHORT: null;
} {
    return value == Direction.LONG ? {
        LONG: null
    } : value == Direction.SHORT ? {
        SHORT: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionTime): {
    NY: null;
} | {
    LONDON: null;
} | {
    ASIAN: null;
} | {
    OTHER: null;
} {
    return value == SessionTime.NY ? {
        NY: null
    } : value == SessionTime.LONDON ? {
        LONDON: null
    } : value == SessionTime.ASIAN ? {
        ASIAN: null
    } : value == SessionTime.OTHER ? {
        OTHER: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketCondition): {
    VOLATILE: null;
} | {
    RANGING: null;
} | {
    CHOPPY: null;
} | {
    OTHER: null;
} | {
    TRENDING: null;
} {
    return value == MarketCondition.VOLATILE ? {
        VOLATILE: null
    } : value == MarketCondition.RANGING ? {
        RANGING: null
    } : value == MarketCondition.CHOPPY ? {
        CHOPPY: null
    } : value == MarketCondition.OTHER ? {
        OTHER: null
    } : value == MarketCondition.TRENDING ? {
        TRENDING: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CsvTradeRow>): Array<_CsvTradeRow> {
    return value.map((x)=>to_candid_CsvTradeRow_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
